-- AlterTable
ALTER TABLE "Groups" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "joindate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
